### ISSUE TITLE
Add fantom factory deployments

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [curvefi/curve-docs#47]
### Core
* Factory `0x686d67265703d1f124c45e33d47d794c566889ba`
* GaugeExtension `0x9fAe78C4bBB649deB7b2295dDB8A03adA7eB660F`

### Metapools 
* MetaUSDBasic (2pool) `0xfCE359115dFe1533a2458650123F86C454BC0213`
* MetaUSDBalances (2pool) `0x09C62ad0694e3f1ad8cF8876aaBe56138C586f5F`
* MetaUSDBasic (geist) `0x210C806F6AE850279f7E298dE749EC4B427d00DD`
* MetaUSDBalance (geist) `0xf82162bB68aD5a168345bb7EFb2faA0EDCCA5177`
* MetaBTCBasic `0xC9438d8928486bD9621D326002F4672bF684187A`
* MetaBTCBalances `0x2b70A5B878665FfDB4A06Ba40a264d6c70f68F4B`

### Zaps
* USD (2pool) `0x78D51EB71a62c081550EfcC0a9F9Ea94B2Ef081c`
* USD (geist) `0x247aEB220E87f24c40C9F86b65d6bd5d3c987B55`
* BTC `0x001E3BA199B4FF4B5B6e97aCD96daFC0E2e4156e`

### Plain (2 coins)
* Plain2Basic `0x61E10659fe3aa93d036d099405224E4Ac24996d0`
* Plain2Balances `0xd9Acb0BAeeD77C99305017821167674Cc7e82f7a`
* Plain2ETH `0xE6358f6a45B502477e83CC1CDa759f540E4459ee`
* Plain2Optimized `0xAD4768F408dD170e62E074188D81A29AE31B8Fd8`

### Plain (3 coins)
* Plain3Basic `0x3cABd83bCa606768939B843f91df8f4963dBC079`
* Plain3Balances `0xD1602F68CC7C4c7B59D686243EA35a9C73B0c6a2`
* Plain3ETH `0x5d58Eb45e97B43e471AF05cD2b11CeB4106E1b1a`
* Plain3Optimized `0x7Ee25A34C921E4009B726cC6be0643fd6a39DbfE`

### Plain (4 coins)
* Plain4Basic `0xABE216918fFDa43B44e3FC09639Fd82fD3527D89`
* Plain4Balances `0x775A21E0dfE25aF30FF2FCAC37512EbD8fD36471`
* Plain4ETH `0xb11Dc44A9f981fAF1669dca6DD40c3cc2554A2ce`
* Plain4Optimized `0x9D7C28226AA7142cBF234ab9aa9C203D095c528B`

**Comment by charlie-eth** [comment]
Where are the zaps, ser?

**Comment by skellet0r** [comment]
BTC Zap - 0x001E3BA199B4FF4B5B6e97aCD96daFC0E2e4156e
USD Zap - 0x78D51EB71a62c081550EfcC0a9F9Ea94B2Ef081c

**Comment by charlie-eth** [comment]
Thanks, I'm @skellet0r pilled. 

Will go live tonight hopefully.
