### ISSUE TITLE
Ava factory deployments (WIP)

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [curvefi/curve-docs#53]
### Core
* Factory: ` 0xb17b674D9c5CB2e441F8e196a2f048A81355d031`
* GaugeExtension: `0x9cf512116fb29ec1dd3798e6ea9a7cd9d18bbed1`

### Metapools 
* MetaUSDBasic `0xa237034249290de2b07988ac64b96f22c0e76fe0`
* MetaUSDBalances `0xc50c05ca1f8c2346664bd0d4a1eb6ac1da38414f`
* MetaBTCBasic `0xa27f39E9C21b3376F43266E13Ad5A5d6E9BdB320`
* MetaBTCBalances `0x505C34ED8dBE96d2D5C7D83158aA844887770970`

### Plain (2 coins)
* Plain2Basic `0x697434ca761d4f86b553784b69f4f37f5edf54df`
* Plain2Balances `0xbdff0c27dd073c119ebcb1299a68a6a92ae607f0`
* Plain2ETH `0x64448B78561690B70E17CBE8029a3e5c1bB7136e`
* Plain2Optimized `0x09672362833d8f703D5395ef3252D4Bfa51c15ca`

### Plain (3 coins)
* Plain3Basic `0x1de7f0866e2c4adAC7b457c58Cc25c8688CDa1f2`
* Plain3Balances `0x094d12e5b541784701FD8d65F11fc0598FBC6332`
* Plain3ETH `0xf1f85a74ad6c64315f85af52d3d46bf715236adc`
* Plain3Optimized `0xaa82ca713d94bba7a89ceab55314f9effeddc78c`

### Plain (4 coins)
* Plain4Basic `0x7544Fe3d184b6B55D6B36c3FCA1157eE0Ba30287`
* Plain4Balances `0x7d86446ddb609ed0f5f8684acf30380a356b2b4c`
* Plain4ETH `0x0eb0F1FaF5F509Ac53fA224477509EAD167cf410`
* Plain4Optimized `0xCE94D3E5b0D80565D7B713A687b39a3Dc81780BA`

**Comment by charlie-eth** [comment]
Zaps please sers @skellet0r ?

**Comment by skellet0r** [comment]
MetaUSDZap: `0x76147c0C989670D106b57763a24410A2a22e335E`
MetaBTCZap: `0x877a7aAEe9EdC34911A2442fB814ece2679Cf3FD`

*Same notation as polygon deployments

**Comment by charlie-eth** [comment]
Thanks!

**Comment by iamdefinitelyahuman** [comment]
aaaaaah!

**Comment by charlie-eth** [comment]
aaaah I'm thaaaanking
