### ISSUE TITLE
Where are your docs published.... 

### ISSUE THREAD

**Issue by richardpringle** [curvefi/curve-docs#6]
I found a bunch of links... most point to some sort of 404

**Comment by iamdefinitelyahuman** [comment]
https://curve.readthedocs.io/en/latest/

**Comment by richardpringle** [comment]
@iamdefinitelyahuman...
![image](https://user-images.githubusercontent.com/3286504/105231584-1c3baf80-5b35-11eb-91f2-578f7df33901.png)

**Comment by iamdefinitelyahuman** [comment]
Ahh sorry, without the /en/latest bit

https://curve.readthedocs.io/
